### ISSUE TITLE
Rename 

### ISSUE THREAD

**Issue by mthenw** [serverless/sdk-nodejs#4]
It's not actually SDK. 

Propositions:
- stdlib  - `require('@serverless/stdlib')`
- lib - `require('@serverless/lib')`

cc @serverless/team

**Comment by pmuens** [comment]
Could you elaborate why it's not an SDK?

I'd vote for `lib` if it's renamed.

**Comment by nikgraf** [comment]
`std` is not so common in the JS world?
`lib` is very generic?

Right now I don't have a better name, but I will think about it 🙂

**Comment by mthenw** [comment]
@pmuens because SDK suggest that it enables to develop/extend framework. This repo is about proving a way set of methods for easier functions communication, wrapping functions, etc.

**Comment by mthenw** [comment]
OK, as IMHO "sdk" might be misleading I'm renaming it to "stdlib" for now. I will provide description in README.
